### ISSUE TITLE
有点小bug求解决

### ISSUE THREAD

**Issue by GLWen** [yuyedaidao/YQSlideMenuControllerDemo#3]
就是我手推着主页不要放，然后同时点击侧栏按钮进行push另外界面的时候，你会发现，主页不会把侧栏盖上去，，而且一直点，会一直push界面出来。

**Comment by GLWen** [comment]
可以留个微信交流下吗？
谢谢！

**Comment by yuyedaidao** [comment]
@GLWen  问题已解决，多谢！现在版本是 0.1.0
